### ISSUE TITLE
6.0 Crash when exiting on MacOS

### ISSUE THREAD

**Issue by kdgarris** [stella-emu/stella#416]
When I exit the Stella 6.0 window by hitting the red circle while a game is still running, the OS reports that Stella exited abnormally.  This does not occur when quitting Stella from the UI when a game is not running.  I have attached the crash report (in ASCII) from the OS.

[stella-crash.txt](https://github.com/stella-emu/stella/files/2873019/stella-crash.txt)

**Comment by sa666666** [comment]
At least one person has reported similar issues in Windows too, so this may be and SDL problem, or something more widespread.

**Comment by kdgarris** [comment]
It looks like this was related to me unknowingly running Stella directly from the disk image instead of the binary copied to the hard drive.  Once I corrected this and launched the intended copy, I could no longer reproduce the crash.

**Comment by sa666666** [comment]
It's still happening for me when I run directly from Xcode; haven't tried with running from the appicon installed on the desktop or anything.  In any event, it shouldn't be happening at all, so I will leave open for now, for further investigation.

**Comment by sa666666** [comment]
Happening in all modes when using the close button and a game is playing.  Seems to be crashing on the sound routines, and related to threading.  I suspect that the 'close' button in macOS is bypassing the normal SDL way of shutting down an app, and crashes as a result.

**Comment by sa666666** [comment]
Source of this crash has been isolated to https://github.com/stella-emu/stella/issues/430.  Fixing that issue will take care of this one.

**Comment by DirtyHairy** [comment]
Should be fixed in 8e22dc52.
