### ISSUE TITLE
KB focus after debugger commands

### ISSUE THREAD

**Issue by andrew-davie** [stella-emu/stella#648]
There seems to be a regression in the focus on debugger entry window.
When I type "reset", or "clearbreaks", etc...  focus is lost and i have to re-click to type more.

**Comment by thrust26** [comment]
I cannot reproduce. Which version are you using?

**Comment by andrew-davie** [comment]
MacOS, Stella 6.2_pre grabbed and built just 2 days ago.
I can grab/rebuild if required.

**Comment by andrew-davie** [comment]
As it happens it failed for the first two i tried...

reset
clearbreaks


It is working OK for others I have tested.
So, only some are failing.

**Comment by thrust26** [comment]
@DirtyHairy @sa666666  Can you reproduce the issue?

**Comment by andrew-davie** [comment]
... and now it's working just fine for me.
Yet it most definitely was not working. Same binary.
I guess we'll have to keep an eye on this one.

**Comment by thrust26** [comment]
There were no hit breakpoints, traps or so involved, right?

**Comment by andrew-davie** [comment]
There may have been breakpoints. But in any case, typing "reset" should not hit them, nor should "clearbreaks". In both those cases, focus should remain with the text entry window.

**Comment by andrew-davie** [comment]
This is **definitely** happening. No breakpoints. Trigger debugger, type "reset" - focus no longer in the debugger text input window and have to reselect with mouse. If it happens at all, then it happens all the time.

**Comment by thrust26** [comment]
Where is the focus then? Always the same place?

**Comment by andrew-davie** [comment]
> Where is the focus then? Always the same place?

I don't know, sorry.  I can't trigger this bug anytime I want.
But one thing I **think** is the case - might be a clue - the black box cursor in the entry window does not appear when the bug happens. Even when you do have e focus in the window and type - there is no black box cursor. I will confirm next time it happens, but that's the best I can do for you right now.

**Comment by andrew-davie** [comment]
OK. Got a screen recording of the bug in action, if required.
But, in any case, the focus is on the "RUN" button top right of screen.

**Comment by andrew-davie** [comment]
> But one thing I **think** is the case - might be a clue - the black box cursor in the entry window does not appear when the bug happens. Even when you do have e focus in the window and type - there is no black box cursor.

The above is incorrect.
As noted, though, focus is on the [RUN] button when this bug happens.

**Comment by thrust26** [comment]
Thanks for the info. That might bring me closer to the root cause, Even though I still cannot reproduce it.

**Comment by andrew-davie** [comment]
[focus.mp4.zip](https://github.com/stella-emu/stella/files/4723711/focus.mp4.zip)

In the enclosed video, you can see the focus switching to [RUN] as I try various things.
It switches (and remains at) [RUN] immediately after I type "reset", for example.

**Comment by thrust26** [comment]
I think I can reproduce it now. It seems to happen when you exist the debugger via 'Run' button. I always use the escape key here (you can use that as a workaround), there is doesn't happen.

**Comment by andrew-davie** [comment]
> I think I can reproduce it now. It seems to happen when you exist the debugger via 'Run' button. I always use the escape key here (you can use that as a workaround), there is doesn't happen.

Confirmed.

**Comment by thrust26** [comment]
@andrew-davie This should be fixed now. Reopen if you find any remaining focus problems.

**Comment by andrew-davie** [comment]
TY. Have the latest version.

This is still not behaving quite the way I would like it to. I would like it to always **always** when I trigger a break (via ~) or hitting a breakpoint... have it ready for keyboard input. That is, focus on the prompt window in all cases when a break is triggered. 

This is not currently the case. If I break (via ~) and click in the prompt window and type 'reset', click [RUN], and trigger another break (via ~) then I no longer have focus in the prompt window.

**Comment by thrust26** [comment]
So the focus is there where you left the debugger. This is intentional and now works as designed.

Some people want to use the prompt, some modify RAM or the CPU or are working in the disassembly, some trace TIA or audio. 

If you do not want the focus to change from the prompt, there are several ways to do so: type 'run' or press ESC or '~'.

**Comment by sa666666** [comment]
Another option is to not have the buttons in the 'focus list'.  So selecting a button would not move focus from wherever it was before clicking the button.  This would 'solve' the problem here, but also not allow users to navigate the UI with the keyboard (ie, you would _have_ to use the mouse to click a button).  So probably not much of a solution after all ...
