### ISSUE TITLE
crash on Ubuntu 18.04 LTS 64-bit -- Stella 6.2.1

### ISSUE THREAD

**Issue by andrew-davie** [stella-emu/stella#694]
The attached binaries both work OK for me on MacOS stella 6.1, 6.2, but the 5PQ8 version has been reported to always crash when run on Ubuntu 18.04 LTS 64-bit, and the 5PQ4 version works.  There are no code differences - just the amount of RAM in use (i.e., for the tree-search, 13 banks vs 9 banks).

I don't know this is a stella bug, but it's something that is behaving differently on different OS's, which is unusual. I'm wondering if there might be a bug in the 3E+ driver, regarding amount of RAM.

[chess.zip](https://github.com/stella-emu/stella/files/5148216/chess.zip)

**Comment by DirtyHairy** [comment]
This sounds like a memory corruption issue, but I cannot reproduce it here, ASAN doesn't show anything. However, 5PQ8 only shows garbage for me, both with 6.2.1 and current git. 5PQ4 works. Banking is detected and set to 3E+.

**Comment by andrew-davie** [comment]
OK, update.
Stella on MacOS runs 5PQ8 "properly", but it does NOT run on actual hardware via UnoCart or PlusCart.
I'm not sure what's going on here - I would expect it to work, but that it doesn't work on hardware means...

1) the drivers in UnoCart and PlusCart have a bug for 3E+. AND. INDEPENDENTLY. Stella has a bug on Ubuntu.
or 2) Stella on MacOS has a bug that lets the game run
and/or 3) The game has a bug that stops it running on hardware, and Stella has a bug that allows it to run on MacOS

I have no idea what's going on ATM.

**Comment by thrust26** [comment]
@andrew-davie Do you have Developer Options enabled? Because when I enable them, I cannot run both games. There are a lot of "reads from write port"/"writes to read ports" happening.

Partially this looks like a bug in Stella (TIA range) and partially like a bug on your side.

Please enable "Developer Options" and then go back until the game start working again. Then we can try to sort out all problems. As of now there seem to be too many factors involved.

**Comment by DirtyHairy** [comment]
I don't believe that there can be difference in behaviour between the different platforms at the level of emulation. The only viable explanation for a game that crashes only on some platforms is memory corruption. If this is the case ASAN should show it, but as I said, I am afraid I cannot even run 5PQ8 on my machine, I just get the attached image. No ASAN errors, though 😛 

<img width="1072" alt="Bildschirmfoto 2020-08-31 um 17 52 26" src="https://user-images.githubusercontent.com/2444224/91739942-e95b4400-ebb2-11ea-83df-09c42a602ebc.png">

**Comment by sa666666** [comment]
I suppose technically, different environments could create different code because different compilers are used, and that could potentially generate errors on one platform and not another.  But I would look at this as only a last resort, since we've received no other reports of similar bugs.

**Comment by sa666666** [comment]
I've tested in all my systems now with various builds (18.04 v/6.2.1, 20.04 v/6.3pre, macOS v/6.2.1, Windows v/6.3_pre), and I'm getting the same results as @DirtyHairy above.  So the fact that it's broken in different versions of Stella, different OS's, _and_ on the hardware cart emulators in exactly the same way, leads me to think there's something in the game code itself doing it.

Also, I tested on bog-standard "player" settings, so no developer options enabled to be messing things up.  I suppose we all (Stella, Unocart, Pluscart) could be implementing 3E+ incorrectly, but if so, I'd need to see evidence of that.

**Comment by thrust26** [comment]
It could be a bug in Stella too. I am currently investigating reads from write ports breaks which shouldn't happen.

**Comment by thrust26** [comment]
After fixing some bugs in Stella, I think I found the chess bug. Note that Y is 15, but the jump tables are not prepared for such large values. 

![chessbug](https://user-images.githubusercontent.com/24360774/91800686-bc964380-ec29-11ea-8a4a-ed0aabcf8663.png)

@andrew-davie Please let us know if we can close this one.

**Comment by andrew-davie** [comment]
Thanks for that @thrust26 

I have downloaded/built the latest Stella.
It seem to me this bug is occurring when the RAM bank I am using is >32
In that case, I am seeing garbage in the board - at this point I don't know if it is my issue with banks or Stella is borking when RAM bank >32.  In any case as you see from the above image, in this case it was 35 (bank 3 in use for the board).

**Comment by thrust26** [comment]
I thought the too high index value in Y is the problem. The tables read with this index are not large enough.

Or is the large index a result of the RAM bank problems you describe?

**Comment by andrew-davie** [comment]
> I thought the too high index value in Y is the problem. The tables read with this index are not large enough (Y = 0..15, but only 8 entries per table).
> 
> Or is the large index a result of the RAM bank problems you describe?

Y is the piece type, retrieved from the board.
The board is in the RAM bank, and it is FULL of meaningless values (pieces).  In other words, the board bank is not anywhere near correct data. And I thought "mmh, and the RAM bank for the board only goes above 32 when I set the #ply for the search to a high value".  So, when the board bank is <32, all seems OK.
That's all I know right now. I thought I'd mention that RAM bank >32 might be an issue worth looking at.

**Comment by thrust26** [comment]
OK, so Y shouldn't be larger than 7 then. But why are you masking the value then? And why with $0F?

I will look into the >= 32 bank issue, but at first glance the code looks fine. Please double check your code there too.

**Comment by andrew-davie** [comment]
> OK, so Y shouldn't be larger than 7 then. But why are you masking the value then? And why with $0F?
> 
> I will look into the >= 32 bank issue, but at first glance the code looks fine. Please double check your code there too.

I could use 7 for the mask; a bug would still be there -- because the board is full of rubbish.
The other bits are used for various flags - colour, if piece has moved, if piece is an en-passant pawn, if piece is involved in castling. The extra bit for the piece types is just a historical accident.
My point being, whatever the bug is, it's not going to be fixed by changing the mask.

**Comment by andrew-davie** [comment]
Having said that.... I changed the mask to 7 and it appears to be running OK.
Will investigate further...!  Ha

**Comment by andrew-davie** [comment]
Given it crashes on hardware, too, it just has to be a bug in my code.

**Comment by thrust26** [comment]
@andrew-davie Can we close this one?

**Comment by andrew-davie** [comment]
> @andrew-davie Can we close this one?

I have been distracted and not yet found the source of this issue.
My question would be - how could i have one version of Stella that works as expected, and the newest version doesn't.
Something has to have changed in the stella code that would give a clue. If not the 3E+ code, then some base class...?
My viewpoint here is that although a bug in my code is probable - based on the clues I've seen so far -- I can't fathom why it's been working OK with stella I have been using, and suddenly doesn't with the newer versions. What changed?
You may close it if you wish - I will track down the bug eventually and can report back.

**Comment by thrust26** [comment]
When you find out which was the exact last version that worked or the first version that crashes, we can look for the differences.

**Comment by andrew-davie** [comment]
"git bisect" is a wonderful tool
9cf4686bc28f111486f6ad780110794e4013d202 is the first bad commit
And when it says "bad commit" I'm not claiming the code is bad.  This is just the first version where my game stopped working as expected.

**Comment by andrew-davie** [comment]
Here is a binary in case any testing needs it...
[chess.bin.zip](https://github.com/stella-emu/stella/files/5183689/chess.bin.zip)

**Comment by thrust26** [comment]
Thanks. I will have a look and try to find out why the ROM fails.

**Comment by andrew-davie** [comment]
> Thanks. I will have a look and try to find out why the ROM fails.

Happy for you to wait until I check things out this end. Maybe I can find more clues, and maybe it's my fault anyway :P

**Comment by thrust26** [comment]
Looks like it was my fault. The code was having problems with e.g. 32K ROMs and RAM banks >= 32.  I just committed a fix, please give it a try and let me know. Thanks!

**Comment by andrew-davie** [comment]
Confirmed fixed. Thank you @thrust26 

Strangely, still doesn't work on PlusCart, and last I checked, UnoCart.
Clearly a similar bug in their implementation...?

**Comment by thrust26** [comment]
Might be. 

@DirtyHairy IIRC you did implement 3E+, maybe you know more?

**Comment by sa666666** [comment]
Did we confirm this is not a bug in Stella?  If so, can we close now?

**Comment by thrust26** [comment]
Yes, no Stella bug.
